import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AlternateEmailIcon from '@mui/icons-material/AlternateEmail';
import GitHubIcon from '@mui/icons-material/GitHub';
import InstagramIcon from '@mui/icons-material/Instagram';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>
      <div className='imagee'>
        <div className='orqafon'>
          <div className='textlar'>
        <h1 className='uptext'>hello I am</h1>
        <h1 id='ortatext'>Bobur Abdukarimov</h1>
        <p>Frontend/dev </p>
      </div>
      <div className='iconlarr'>
        <span className='textIcon'>
          <a href="https://account.mail.ru/login?allow_external=1&opener=mail.login">
              <AlternateEmailIcon/></a>
        </span>
        <span className='textIcon'>
          <a href="https://github.com/bobur2003">
            <GitHubIcon/>
          </a>
          </span>
        <span className='textIcon'>
          <a href="https://www.instagram.com/webdev_js1/"><InstagramIcon/></a>
          </span>
      </div>
        </div>
      </div>
    </div>
  )
}
