import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AlternateEmailIcon from '@mui/icons-material/AlternateEmail';
import GitHubIcon from '@mui/icons-material/GitHub';
import InstagramIcon from '@mui/icons-material/Instagram';
import Link from 'next/link';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" 
      integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
      crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <div className='imagee'>
        <div className='orqafon'>
          <div className='textlar'>
        <h1 className='uptext'>hello, I'm</h1>
        <h1 id='ortatext'>Bobur Abdukarimov</h1>
        <p>Frontend/dev </p>
      </div>
      <div className='iconlarr'>
        <span className='textIcon'>
          <Link href={"https://account.mail.ru/login?allow_external=1&opener=mail.login"}>
              <AlternateEmailIcon/></Link>
        </span>
        <span className='textIcon'>
          <Link href={"https://github.com/bobur2003"} >
            <GitHubIcon/>
          </Link>
          </span>
        <span className='textIcon'>
          <Link href={"https://www.instagram.com/webdev_js1/"}><InstagramIcon/></Link>
          </span>
      </div>
        </div>
      </div>
    </div>
  )
}
